# seperate installation for karpenter crd is needed since when you upgarde karpenter, it does not auto upgrade the crds. Seperating the crds and karpeneter install allows you to update both independently

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: karpenter-crd
  namespace: karpenter
spec:
  type: "oci"
  url: oci://public.ecr.aws/karpenter-crd/

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karpenter-crd
  namespace: karpenter
spec:
  chart:
    spec:
      chart: karpenter-crd
      version: 1.8.2 # mentioning the "v" at the beginning will not work here
      interval: 10m0s # this is the interval for checking the chart i.e. version
      sourceRef:
        kind: HelmRepository
        name: karpenter-crd
  releaseName: karpenter-crd
  targetNamespace: karpenter # this is where to deploy the resources
  interval: 10m0s # this is the interval for checking the release i.e. deployment of the chart